server {
    listen 8000;
    server_name _;
    root /usr/share/nginx/html;

    location = /visualizer {
        return 301 /visualizer/;
    }

    location /visualizer/ {
        rewrite ^/visualizer/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
